dynfilter_odom:
  ros__parameters:
    "dyn_obj/points_topic": "/cloud_registered_body"
    "dyn_obj/odom_topic": "/aft_mapped_to_init"
    "dyn_obj/frame_id": "camera_init"
    "dyn_obj/use_odom": true
    "dyn_obj/static_pos": [0.0, 0.0, 0.0]
    "dyn_obj/static_quat": [1.0, 0.0, 0.0, 0.0]
    "dyn_obj/pc_topic": "/livox/lidar"

    "dyn_obj/dataset": 4 #0 for kitti, 1 for nuscenes, 2 for waymo
    "dyn_obj/buffer_delay": 0.1
    "dyn_obj/buffer_size": 100000
    "dyn_obj/points_num_perframe": 30000
    "dyn_obj/depth_map_dur": 0.4
    "dyn_obj/max_depth_map_num": 5
    "dyn_obj/max_pixel_points": 20
    "dyn_obj/frame_dur": 0.02
    "dyn_obj/self_x_f": 0.0
    "dyn_obj/self_x_b": 0.0
    "dyn_obj/self_y_l": 0.0
    "dyn_obj/self_y_r": 0.0
    "dyn_obj/blind_dis": 0.3
    "dyn_obj/fov_up": 52.0
    "dyn_obj/fov_down": -7.0
    "dyn_obj/fov_left": 180.0
    "dyn_obj/fov_right": -180.0
    "dyn_obj/fov_cut": -20.0

    "dyn_obj/depth_thr1": 0.5
    "dyn_obj/enter_min_thr1": 0.5
    "dyn_obj/enter_max_thr1": 0.5 ##10.3
    "dyn_obj/map_cons_depth_thr1": 0.5
    "dyn_obj/map_cons_hor_thr1": 0.05
    "dyn_obj/map_cons_ver_thr1": 0.05
    "dyn_obj/map_cons_hor_dis1": 0.3
    "dyn_obj/map_cons_ver_dis1": 0.6
    "dyn_obj/depth_cons_depth_thr1": 0.5
    "dyn_obj/depth_cons_depth_max_thr1": 1.0
    "dyn_obj/depth_cons_hor_thr1": 0.05
    "dyn_obj/depth_cons_ver_thr1": 0.05
    "dyn_obj/enlarge_z_thr1": -2.5
    "dyn_obj/enlarge_angle": 2.0
    "dyn_obj/enlarge_depth": 3.0
    "dyn_obj/occluded_map_thr1": 3
    "dyn_obj/case1_interp_en": true

    "dyn_obj/v_min_thr2": 0.5
    "dyn_obj/acc_thr2": 7.0
    "dyn_obj/map_cons_depth_thr2": 0.3
    "dyn_obj/map_cons_hor_thr2": 0.02
    "dyn_obj/map_cons_ver_thr2": 0.06
    "dyn_obj/occ_depth_thr2": 0.3
    "dyn_obj/occ_hor_thr2": 0.02 ##0.01
    "dyn_obj/occ_ver_thr2": 0.06 ##0.015
    "dyn_obj/depth_cons_depth_thr2": 0.1
    "dyn_obj/depth_cons_depth_max_thr2": 0.5
    "dyn_obj/depth_cons_hor_thr2": 0.03
    "dyn_obj/depth_cons_ver_thr2": 0.06
    "dyn_obj/occluded_times_thr2": 3
    "dyn_obj/k_depth2": 0.005
    "dyn_obj/case2_interp_en": false

    "dyn_obj/v_min_thr3": 0.5
    "dyn_obj/acc_thr3": 15.0
    "dyn_obj/map_cons_depth_thr3": 0.1
    "dyn_obj/map_cons_hor_thr3": 0.03
    "dyn_obj/map_cons_ver_thr3": 0.03
    "dyn_obj/occ_depth_thr3": 0.15
    "dyn_obj/occ_hor_thr3": 0.03
    "dyn_obj/occ_ver_thr3": 0.03
    "dyn_obj/depth_cons_depth_thr3": 0.3
    "dyn_obj/depth_cons_depth_max_thr3": 1.0
    "dyn_obj/depth_cons_hor_thr3": 0.03
    "dyn_obj/depth_cons_ver_thr3": 0.03
    "dyn_obj/occluded_times_thr3": 3
    "dyn_obj/case3_interp_en": false

    "dyn_obj/interp_hor_thr": 0.03
    "dyn_obj/interp_ver_thr": 0.03
    "dyn_obj/interp_thr1": 0.5
    "dyn_obj/interp_static_max": 10.0
    "dyn_obj/interp_start_depth1": 10.0
    "dyn_obj/interp_kp1": 0.1
    "dyn_obj/interp_kd1": 0.5
    "dyn_obj/interp_bg": 0.8
    "dyn_obj/interp_thr2": 0.25
    "dyn_obj/interp_thr3": 0.05

    "dyn_obj/point_index": -1
    "dyn_obj/debug_x": 7.2065
    "dyn_obj/debug_y": -3.1844
    "dyn_obj/debug_z": -0.89005
    "dyn_obj/cluster_coupled": true
    "dyn_obj/cluster_future": true
    "dyn_obj/cluster_extend_pixel": 3
    "dyn_obj/cluster_min_pixel_number": 1
    "dyn_obj/cluster_thrustable_thresold": 0.1
    "dyn_obj/cluster_Voxel_revolusion": 0.1
    "dyn_obj/cluster_async": false
    "dyn_obj/cluster_queue_size": 2
    "dyn_obj/dyn_points_stable_en": true
    "dyn_obj/dyn_points_accu_limit": 3
    "dyn_obj/dyn_points_voxel": 0.4
    "dyn_obj/track_enable": true
    "dyn_obj/track_min_hits": 3
    "dyn_obj/track_max_age": 5
    "dyn_obj/track_min_points": 30
    "dyn_obj/track_gate": 1.5
    "dyn_obj/aabb_alpha": 0.6


    "dyn_obj/dyn_filter_en": true

    "dyn_obj/ver_resolution_max": 0.04 
    "dyn_obj/hor_resolution_max": 0.025
