dynfilter_odom:
  ros__parameters:
    "dyn_obj/points_topic": "/cloud_registered_body"
    "dyn_obj/odom_topic": "/aft_mapped_to_init"
    "dyn_obj/frame_id": "camera_init"
    "dyn_obj/use_odom": true
    "dyn_obj/static_pos": [0.0, 0.0, 0.0]
    "dyn_obj/static_quat": [1.0, 0.0, 0.0, 0.0]
    "dyn_obj/pc_topic": "/velodyne_points"

    "dyn_obj/dataset": 0 #0 for kitti, 1 for nuscenes, 2 for waymo, 3 for avia
    "dyn_obj/use_odom_file": true
    "dyn_obj/stop_object_detect": false
    "dyn_obj/buffer_delay": 0.1
    "dyn_obj/buffer_size": 300000
    "dyn_obj/points_num_perframe": 150000
    "dyn_obj/depth_map_dur": 0.1
    "dyn_obj/max_depth_map_num": 7
    "dyn_obj/max_pixel_points": 50
    "dyn_obj/frame_dur": 0.1
    "dyn_obj/self_x_f": 2.5
    "dyn_obj/self_x_b": -1.5
    "dyn_obj/self_y_l": 0 #1.6
    "dyn_obj/self_y_r": -0 #1.6
    "dyn_obj/blind_dis": 0.3
    "dyn_obj/fov_up": 2.0
    "dyn_obj/fov_down": -23.0
    "dyn_obj/fov_left": 180.0
    "dyn_obj/fov_right": -180.0
    "dyn_obj/fov_cut": -20.0
    "dyn_obj/checkneighbor_range": 1

    "dyn_obj/depth_thr1": 0.15
    "dyn_obj/enter_min_thr1": 1.0 # kill car front points (close to wall, related to view change)
    "dyn_obj/enter_max_thr1": 0.3 # equal to map_cons_depth_thr1, for save pedestrain close to wall
    "dyn_obj/map_cons_depth_thr1": 0.3
    "dyn_obj/map_cons_hor_thr1": 0.01
    "dyn_obj/map_cons_ver_thr1": 0.015
    "dyn_obj/map_cons_hor_dis1": 0.15
    "dyn_obj/map_cons_ver_dis1": 0.15
    "dyn_obj/depth_cons_depth_thr1": 0.5
    "dyn_obj/depth_cons_depth_max_thr1": 1.0
    "dyn_obj/depth_cons_hor_thr1": 0.01
    "dyn_obj/depth_cons_ver_thr1": 0.01
    "dyn_obj/enlarge_z_thr1": -2.5
    "dyn_obj/enlarge_angle": 2.0
    "dyn_obj/enlarge_depth": 3.0
    "dyn_obj/occluded_map_thr1": 2
    "dyn_obj/case1_interp_en": true

    "dyn_obj/v_min_thr2": 1.0
    "dyn_obj/acc_thr2": 7.0
    "dyn_obj/map_cons_depth_thr2": 0.2
    "dyn_obj/map_cons_hor_thr2": 0.01
    "dyn_obj/map_cons_ver_thr2": 0.01
    "dyn_obj/occ_depth_thr2": 10.15
    "dyn_obj/occ_hor_thr2": 0.01
    "dyn_obj/occ_ver_thr2": 0.015
    "dyn_obj/depth_cons_depth_thr2": 0.1
    "dyn_obj/depth_cons_depth_max_thr2": 0.5
    "dyn_obj/depth_cons_hor_thr2": 0.01
    "dyn_obj/depth_cons_ver_thr2": 0.01
    "dyn_obj/occluded_times_thr2": 2
    "dyn_obj/k_depth2": 0.005
    "dyn_obj/case2_interp_en": false

    "dyn_obj/v_min_thr3": 0.5
    "dyn_obj/acc_thr3": 15.0
    "dyn_obj/map_cons_depth_thr3": 0.2
    "dyn_obj/map_cons_hor_thr3": 0.01
    "dyn_obj/map_cons_ver_thr3": 0.008
    "dyn_obj/occ_depth_thr3": 0.15
    "dyn_obj/occ_hor_thr3": 0.01
    "dyn_obj/occ_ver_thr3": 0.01
    "dyn_obj/depth_cons_depth_thr3": 0.3
    "dyn_obj/depth_cons_depth_max_thr3": 1.0
    "dyn_obj/depth_cons_hor_thr3": 0.01
    "dyn_obj/depth_cons_ver_thr3": 0.01
    "dyn_obj/occluding_times_thr3": 2
    "dyn_obj/case3_interp_en": false

    "dyn_obj/interp_hor_thr": 0.015
    "dyn_obj/interp_ver_thr": 0.007
    "dyn_obj/interp_thr1": 0.5
    "dyn_obj/interp_static_max": 10.0
    "dyn_obj/interp_start_depth1": 10.0
    "dyn_obj/interp_kp1": 0.1
    "dyn_obj/interp_kd1": 0.5
    # interp_bg: 0.8
    "dyn_obj/interp_thr2": 0.25
    "dyn_obj/interp_thr3": 0.05

    "dyn_obj/point_index": -1 
    "dyn_obj/debug_x": 7.2065
    "dyn_obj/debug_y": -3.1844
    "dyn_obj/debug_z": -0.89005

    "dyn_obj/cluster_coupled": true
    "dyn_obj/cluster_future": true
    "dyn_obj/cluster_extend_pixel": 2
    "dyn_obj/cluster_min_pixel_number": 8
    "dyn_obj/cluster_thrustable_thresold": 0.3
    "dyn_obj/cluster_Voxel_revolusion": 0.3
    "dyn_obj/cluster_async": false
    "dyn_obj/cluster_queue_size": 2
    "dyn_obj/dyn_points_stable_en": true
    "dyn_obj/dyn_points_accu_limit": 3
    "dyn_obj/dyn_points_voxel": 0.4
    "dyn_obj/track_enable": true
    "dyn_obj/track_min_hits": 3
    "dyn_obj/track_max_age": 5
    "dyn_obj/track_min_points": 30
    "dyn_obj/track_gate": 1.5
    "dyn_obj/aabb_alpha": 0.6

    "dyn_obj/dyn_filter_en": false
    "dyn_obj/debug_publish": false

    "dyn_obj/ver_resolution_max": 0.007
    "dyn_obj/hor_resolution_max": 0.005

